CREATE TABLE public.arsip_surat_keluar (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nama_pemohon text,
    no_surat text NOT NULL,
    tanggal_surat date NOT NULL,
    perihal text,
    penanggung_jawab text,
    tanggal_pengiriman date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT arsip_surat_keluar_pkey PRIMARY KEY (id)
);

ALTER TABLE public.arsip_surat_keluar ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users
CREATE POLICY "Allow authenticated users to read arsip_surat_keluar" ON public.arsip_surat_keluar FOR SELECT TO authenticated USING (true);

-- Grant all permissions to service_role for admin operations
CREATE POLICY "Allow service_role to manage arsip_surat_keluar" ON public.arsip_surat_keluar FOR ALL TO service_role USING (true);

-- Grant insert permissions for authenticated users, as the function runs under their role
CREATE POLICY "Allow authenticated users to insert into arsip_surat_keluar" ON public.arsip_surat_keluar FOR INSERT TO authenticated WITH CHECK (true);
