// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzivgwvreceohmqmtvqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6aXZnd3ZyZWNlb2htcW10dnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjExNjYsImV4cCI6MjA2NTA5NzE2Nn0._B7-kXD91zlgxXUqSVNceFM-TrOkLN88Lg3SOTMg2lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);